name: Check Pull Request

on:
  pull_request:
    types: 
    - opened
    - reopened
    - edited
    - synchronize

jobs:
  call-workflow:
    uses: dhis2/workflows/.github/workflows/link-jira-issues.yml@master
    secrets: inherit
